### PR TITLE
Fix test_strong_run_exports_from_build_applies_to_host

### LINKED ISSUE #5791: CI broken due to `tests/test_subpackages.py::test_strong_run_exports_from_build_applies_to_host`
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

CI won't get green due to this reproducible error:

```
tests/test_subpackages.py::test_strong_run_exports_from_build_applies_to_host
```

I think this is due to:

```
stat: $PREFIX/lib/libc++.dylib: stat: No such file or directory
```

Which is part of the [`build.sh` script](https://github.com/conda/conda-build/blob/02e0a8c862e6c658c7800993c16740a5c9976b2f/tests/test-recipes/split-packages/_strong_run_exports_applies_from_build_to_host/build.sh) in that test.

This file should be in the `libcxx` package for osx in `defaults`, but [latest version (v19)](https://conda-metadata-app.streamlit.app/?q=pkgs%2Fmain%2Fosx-64%2Flibcxx-19.1.7-haebbb44_3.conda) only contains:

```
lib/libc++.1.0.dylib
lib/libc++.1.dylib
```

While the [previous one (v17)](https://conda-metadata-app.streamlit.app/?q=pkgs%2Fmain%2Fosx-64%2Flibcxx-17.0.6-hf547dac_4.conda) had:

```
lib/libc++.1.0.dylib
lib/libc++.1.dylib
lib/libc++.a
lib/libc++.dylib
lib/libc++experimental.a
```

Probably a packaging bug, but we can make this test more resilient with some globs, I guess. (Or checking the existence of the equivalent `conda-meta/*.json` file.

### Conda Info

```shell
See https://github.com/conda/conda-build/actions/runs/17806802945/job/50627505768?pr=5790
```

### Conda Config

```shell
See https://github.com/conda/conda-build/actions/runs/17806802945/job/50627505768?pr=5790
```

### Conda list

```shell
See https://github.com/conda/conda-build/actions/runs/17806802945/job/50627505768?pr=5790
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jsmolic**
The test is failing due to the hardcoded check for `libc++.dylib`, however libcxx19 package contains only versioned libraries, so update the check to detect both versioned and unversioned library files

Closes: https://github.com/conda/conda-build/issues/5791

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda-build/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

File: tests/test-recipes/split-packages/_strong_run_exports_applies_from_build_to_host/build.sh [hunk 1]
```diff
@@ -1 +1 @@
-stat $PREFIX/lib/libc++.dylib
+stat $PREFIX/lib/libc++*.dylib
```
Comment (jaimergp) [inline tests/test-recipes/split-packages/_strong_run_exports_applies_from_build_to_host/build.sh]: Should this include the period _before_ the glob?

```suggestion
stat $PREFIX/lib/libc++.*dylib
```

**Comment by jaimergp** [comment]
The PR failures are fixed by https://github.com/conda/conda-build/pull/5790, which in turn has failures fixed in this PR. We'll have to merge both with dirty CI but I think that's ok.

**Review by kenodegard — APPROVED** [review]
